### ISSUE TITLE
Standalone version 2.1.0 fails to start

### ISSUE THREAD

**Issue by grobmeier** [apache/logging-chainsaw#22]
When downloading the standalone version of Chainsaw, the bin/chainsaw command (on OSX) will fail:

```
./bin/chainsaw
➜  apache-chainsaw-2.1.0 Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:990)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:593)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:515)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:484)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:430)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:397)
	at org.apache.log4j.chainsaw.ApplicationPreferenceModelSaver.loadSettings(ApplicationPreferenceModelSaver.java:53)
	at org.apache.log4j.chainsaw.prefs.SettingsManager.configure(SettingsManager.java:302)
	at org.apache.log4j.chainsaw.LogUI.main(LogUI.java:211)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Comparator java.util.TreeMap.comparator accessible: module java.base does not "opens java.util" to unnamed module @689349f1
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.thoughtworks.xstream.core.util.Fields.locate(Fields.java:40)
	at com.thoughtworks.xstream.converters.collections.TreeMapConverter.<clinit>(TreeMapConverter.java:50)
	... 9 more
```

**Comment by rm5248** [comment]
xstream is not in the latest master(removed here:https://github.com/apache/logging-chainsaw/commit/75bedf98665188eef4d13e4bfbb4b0dae456f65e)

**Comment by grobmeier** [comment]
This is the published and downloaded version 2.1.0, I didn't build this from master. Is 2.1 published with this commit?

**Comment by rm5248** [comment]
no, that was done after 2.1 was released

**Comment by grobmeier** [comment]
The binary works using Java 11 and 15, but NOT with Java 8 or with Java 17.

**Comment by tarekahf** [comment]
I used Java 11 and it worked.
